# Docker compose file for the HELK
# HELK build version: 0.9 (BETA Script)
# Author: Roberto Rodriguez @Cyb3rWard0g
# ELK Version: 5x

version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    volumes:
      - ./elasticsearch/docker/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - helk
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.1
    volumes:
      - ./kibana/docker/config/kibana.yml:/usr/share/config/kibana/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - helk
  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.1
    volumes:
      - ./logstash/docker/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - helk
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/docker/htpasswd.users:/etc/nginx/htpasswd.users
    ports:
      - "80:80"
    depends_on:
      - kibana
    networks:
      - helk
  rabbitmq:
    image: specterops/ace-rabbitmq:firsttry
    hostname: "ace-rabbitmq"
    labels:
      NAME: "ace-rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "P@ssw0rd!"
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - elasticsearch
    networks:
      - helk

networks:

  helk:
    driver: bridge
