name: "cobalt_strike_msagent"
index: logs-endpoint-winevent-*
filter:
 - query:
      query_string:
        query: "pipe_name:msagent_*"
type: any
alert:
- slack
slack_webhook_url: "YOUR OWN SLACK WEBHOOK URL"