name: "cobalt_strike_rundll32"
index: logs-endpoint-winevent-*
filter:
 - query:
      query_string:
        query: "process_command_line.keyword:\"C:\\Windows\\system32\\rundll32.exe\"""
type: any
alert:
- slack
slack_webhook_url: "YOUR OWN SLACK WEBHOOK URL"