name: "psexec_psh"
index: logs-endpoint-winevent-*
filter:
 - query:
      query_string:
        query: "registry_key_value:(COMSPEC OR powershell.exe) OR service_image_path:(COMSPEC OR powershell.exe)"
type: any
alert:
- slack
slack_webhook_url: "YOUR OWN SLACK WEBHOOK URL"