name: "whoami"
index: logs-endpoint-winevent-*
filter:
 - query:
      query_string:
        query: "process_command_line: whoami"
type: any
alert:
- slack
slack_webhook_url: "YOUR OWN SLACK WEBHOOK URL"